In [ ]:
import os

os.environ['KAGGLE_USERNAME'] = "add_kaggle_username" # username from the json file
os.environ['KAGGLE_KEY'] = "add_kaggle_key" # key from the json file


!kaggle datasets download -d dhruvildave/dogecoin-historical-data

dogecoin-historical-data.zip: Skipping, found more recently modified local copy (use --force to force download)


In [ ]:
import zipfile
with zipfile.ZipFile('path_of_zip_file', 'r') as zip_ref:
    zip_ref.extractall('path_to_extract')

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [ ]:
df = pd.read_csv('DOGE-USD.csv')

In [ ]:
df.head()

Date      Open      High       Low     Close   Volume
0  2017-11-09  0.001207  0.001415  0.001181  0.001415  6259550
1  2017-11-10  0.001421  0.001431  0.001125  0.001163  4246520
2  2017-11-11  0.001146  0.001257  0.001141  0.001201  2231080
3  2017-11-12  0.001189  0.001210  0.001002  0.001038  3288960
4  2017-11-13  0.001046  0.001212  0.001019  0.001211  2481270

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1532 entries, 0 to 1531
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Date    1532 non-null   object 
 1   Open    1532 non-null   float64
 2   High    1532 non-null   float64
 3   Low     1532 non-null   float64
 4   Close   1532 non-null   float64
 5   Volume  1532 non-null   int64  
dtypes: float64(4), int64(1), object(1)
memory usage: 71.9+ KB


In [ ]:
df.describe()

Open         High          Low        Close        Volume
count  1532.000000  1532.000000  1532.000000  1532.000000  1.532000e+03
mean      0.053032     0.056574     0.049593     0.053151  1.049954e+09
std       0.106257     0.114770     0.097944     0.106358  3.809881e+09
min       0.001046     0.001210     0.001002     0.001038  1.431720e+06
25%       0.002494     0.002551     0.002430     0.002495  1.965492e+07
50%       0.003161     0.003260     0.003059     0.003162  6.806869e+07
75%       0.009115     0.009615     0.008515     0.009195  2.837324e+08
max       0.687801     0.737567     0.608168     0.684777  6.941068e+10

In [ ]:
df['prediction'] = df[['Close']].shift(-1)

In [ ]:
df['prediction'].fillna(value=df['prediction'].mean(),inplace=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1532 entries, 0 to 1531
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Date        1532 non-null   object 
 1   Open        1532 non-null   float64
 2   High        1532 non-null   float64
 3   Low         1532 non-null   float64
 4   Close       1532 non-null   float64
 5   Volume      1532 non-null   int64  
 6   prediction  1532 non-null   float64
dtypes: float64(5), int64(1), object(1)
memory usage: 83.9+ KB


In [ ]:
df.describe()

Open         High          Low        Close        Volume  \
count  1532.000000  1532.000000  1532.000000  1532.000000  1.532000e+03   
mean      0.053032     0.056574     0.049593     0.053151  1.049954e+09   
std       0.106257     0.114770     0.097944     0.106358  3.809881e+09   
min       0.001046     0.001210     0.001002     0.001038  1.431720e+06   
25%       0.002494     0.002551     0.002430     0.002495  1.965492e+07   
50%       0.003161     0.003260     0.003059     0.003162  6.806869e+07   
75%       0.009115     0.009615     0.008515     0.009195  2.837324e+08   
max       0.687801     0.737567     0.608168     0.684777  6.941068e+10   

        prediction  
count  1532.000000  
mean      0.053185  
std       0.106349  
min       0.001038  
25%       0.002496  
50%       0.003162  
75%       0.009279  
max       0.684777

In [ ]:
X = np.array(df['Close'])
X = np.reshape(X, (-1, 1))
y = np.array(df['prediction'])


In [ ]:
X

array([[0.001415],
       [0.001163],
       [0.001201],
       ...,
       [0.177176],
       [0.171145],
       [0.166144]])

In [ ]:
y

array([0.001163  , 0.001201  , 0.001038  , ..., 0.171145  , 0.166144  ,
       0.05318503])

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15)


In [ ]:
from sklearn.ensemble import RandomForestRegressor
rnd=RandomForestRegressor(n_estimators=12,random_state=507)

In [ ]:
rnd.fit(X_train,y_train)

RandomForestRegressor(n_estimators=12, random_state=507)

In [ ]:
rnd.score(X_test,y_test)

0.9623462640695337

In [ ]:
import joblib

filename = 'finalized_model.sav'
joblib.dump(rnd, filename)

['finalized_model.sav']

In [ ]:
model = joblib.load(filename)

In [ ]:
model.predict(X_test)

array([0.33211533, 0.00374883, 0.1710795 , 0.005996  , 0.00318533,
       0.00482117, 0.00738975, 0.00205964, 0.27464125, 0.05186533,
       0.00253083, 0.00926883, 0.00239821, 0.180349  , 0.0034385 ,
       0.24890567, 0.00594575, 0.00263765, 0.26439625, 0.00286817,
       0.00205967, 0.00208075, 0.00325125, 0.00264395, 0.171317  ,
       0.22479183, 0.00353567, 0.00260167, 0.23578792, 0.00403975,
       0.00193825, 0.27778   , 0.00234144, 0.00191217, 0.00261397,
       0.0033281 , 0.00488917, 0.00180717, 0.00248792, 0.0020335 ,
       0.20564675, 0.00769417, 0.0043605 , 0.0024909 , 0.05013808,
       0.00252908, 0.00263556, 0.00335717, 0.00294908, 0.00258425,
       0.0023925 , 0.469444  , 0.00286817, 0.00196367, 0.0022895 ,
       0.00452783, 0.05829283, 0.0027765 , 0.00260665, 0.00279511,
       0.21982508, 0.0060265 , 0.007837  , 0.00309192, 0.00360646,
       0.00263512, 0.00625508, 0.00227529, 0.001982  , 0.00286252,
       0.003418  , 0.28852092, 0.00296283, 0.16272483, 0.00232